services:
  postgres:
    image: postgres:15-alpine
    container_name: mediscope_db
    environment:
      POSTGRES_USER: mediscope_user
      POSTGRES_PASSWORD: mediscope_password
      POSTGRES_DB: mediscope
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: mediscope_pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mediscope.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: mediscope_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: mediscope_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mediscope_app:
    build: .
    container_name: mediscope_core
    depends_on:
      - postgres
      - kafka
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./main.py:/app/main.py
    environment:
      - ENVIRONMENT=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=mediscope_user
      - DB_PASSWORD=mediscope_password
      - DB_NAME=mediscope
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    command: tail -f /dev/null

volumes:
  pgdata: